"use client";

import {FormEvent,useEffect,useState} from "react";

type Submission={id:string;student_name:string|null;grade:string|null;academic_year:string|null;form_data:Record<string,unknown>;status:string;submitted_at:string};

export default function AdminPage(){
 const[rows,setRows]=useState<Submission[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[token,setToken]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 const base=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim().replace(/\/$/,"").replace(/\/rest\/v1.*$/,"");
 const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim();
 useEffect(()=>{const saved=sessionStorage.getItem("rb-admin-token");if(saved){setToken(saved);load(saved)}},[]);
 async function load(accessToken=token){if(!base||!key||!accessToken)return;setLoading(true);setMessage("");try{const r=await fetch(`${base}/rest/v1/student_pathways?select=*&order=submitted_at.desc`,{headers:{apikey:key,Authorization:`Bearer ${accessToken}`}});if(!r.ok)throw new Error(r.status===401?"Session expired. Please sign in again.":`Unable to load submissions (HTTP ${r.status}).`);setRows(await r.json())}catch(e){setMessage(e instanceof Error?e.message:"Unable to load submissions.");if(String(e).includes("expired")){sessionStorage.removeItem("rb-admin-token");setToken("")}}finally{setLoading(false)}}
 async function login(e:FormEvent){e.preventDefault();if(!base||!key){setMessage("Supabase configuration is missing.");return}setLoading(true);setMessage("");try{const r=await fetch(`${base}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const body=await r.json();if(!r.ok)throw new Error(body?.error_description||body?.msg||"Sign-in failed.");sessionStorage.setItem("rb-admin-token",body.access_token);setToken(body.access_token);setPassword("");await load(body.access_token)}catch(e){setMessage(e instanceof Error?e.message:"Sign-in failed.")}finally{setLoading(false)}}
 function logout(){sessionStorage.removeItem("rb-admin-token");setToken("");setRows([]);setPassword("")}
 if(!token)return <main className="admin-page"><div className="admin-login"><a className="admin-brand" href="/"><b>R</b><span>REDBRIDGE<small>PRIVATE ADMIN</small></span></a><p className="admin-kicker">AUTHORIZED ACCESS ONLY</p><h1>Submissions dashboard</h1><p>Sign in with the administrator account created in Supabase.</p><form onSubmit={login}><label>Email<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form>{message&&<div className="admin-error">{message}</div>}</div></main>;
 return <main className="admin-page dashboard"><div className="admin-top"><div><p className="admin-kicker">REDBRIDGE · UNIVERSITY COUNSEL</p><h1>Student submissions</h1><p>{rows.length} questionnaire{rows.length===1?"":"s"}</p></div><div className="admin-actions"><button onClick={()=>load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button><button className="secondary" onClick={logout}>Log out</button></div></div>{message&&<div className="admin-error">{message}</div>}<div className="submission-list">{!loading&&rows.length===0&&!message&&<div className="empty">No submissions yet.</div>}{rows.map(row=><details className="submission" key={row.id}><summary><div><strong>{row.student_name||"Unnamed student"}</strong><span>Grade {row.grade||"—"} · {row.academic_year||"—"}</span></div><time>{new Date(row.submitted_at).toLocaleString()}</time></summary><div className="submission-body"><div className="meta"><span>Status: <b>{row.status}</b></span><span>Record ID: {row.id}</span></div><div className="answer-grid">{Object.entries(row.form_data||{}).map(([label,value])=><div className="answer" key={label}><small>{label.replaceAll("_"," ")}</small><p>{Array.isArray(value)?value.join(", "):typeof value==="object"?JSON.stringify(value):String(value||"—")}</p></div>)}</div></div></details>)}</div></main>
}
