"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Value=string|string[]|number|boolean|null|undefined;
type Submission={id:string;application_number:string;student_name:string|null;grade:string|null;academic_year:string|null;form_data:Record<string,Value>;status:string;submitted_at:string;updated_at:string};
const labels:Record<string,string>={birth_date:"Date of birth",class_teacher:"Homeroom teacher",counselor:"School counselor",parent_name:"Parent / guardian",contact:"Contact",academic_strengths:"Academic strengths",academic_risks:"Academic development areas",personal_strengths:"Personal strengths",personal_risks:"Personal development areas",school_direction:"School recommendation",school_comment:"School observations",parent_strengths:"Strengths identified by family",parent_improve:"Skills to improve",parent_interests:"Interests noted by family",parent_career:"Career ideas / exclusions",directions:"Preferred pathways",priority1:"Family priority 1",priority2:"Family priority 2",priority3:"Family priority 3",countries_main:"Primary destinations",countries_ok:"Acceptable destinations",countries_safe:"Backup destinations",countries_no:"Excluded destinations",country_conditions:"Important destination conditions",budget_max:"Maximum annual budget",budget_comfort:"Comfortable annual budget",without_scholarship:"Can fund without scholarship",scholarship:"Required scholarship",uni_priorities:"University priorities",financial_notes:"Financial considerations",student_subjects:"Student’s favourite subjects",task_types:"Preferred task types",student_career:"Student’s career interest",student_country:"Preferred study environment",extra_hours:"Additional study commitment",activities:"Activities commitment",student_change:"Change student is ready to make",major:"Primary major",major_alt:"Alternative major",priority_subjects:"Priority subjects",english_target:"English target",exams:"Required external exams",key_profile:"Key profile",gap_academic:"Academic gap analysis",gap_exams:"English and exams gap",gap_portfolio:"Portfolio and leadership gap",kpi_academic:"Academic KPI",kpi_english:"English KPI",kpi_attendance:"Attendance KPI",kpi_portfolio:"Portfolio KPI",risks:"Admission risks",final_comment:"Counselor’s final comment",next_review:"Next roadmap review"};
const groups=[
 {title:"Academic & school profile",icon:"A",keys:["academic_strengths","academic_risks","personal_strengths","personal_risks","school_direction","school_comment"]},
 {title:"Family perspective",icon:"F",keys:["parent_strengths","parent_improve","parent_interests","parent_career","directions","priority1","priority2","priority3"]},
 {title:"Destinations & funding",icon:"$",keys:["countries_main","countries_ok","countries_safe","countries_no","country_conditions","budget_max","budget_comfort","without_scholarship","scholarship","uni_priorities","financial_notes"]},
 {title:"Student voice",icon:"S",keys:["student_subjects","task_types","student_career","student_country","extra_hours","activities","student_change"]},
 {title:"University strategy",icon:"U",keys:["major","major_alt","priority_subjects","english_target","exams","key_profile","gap_academic","gap_exams","gap_portfolio"]},
 {title:"KPIs & review",icon:"K",keys:["kpi_academic","kpi_english","kpi_attendance","kpi_portfolio","risks","final_comment","next_review"]}
];
const pretty=(v:Value)=>Array.isArray(v)?v.join(", "):v===null||v===undefined||v===""?"—":String(v);
const human=(key:string)=>labels[key]||key.replaceAll("_"," ").replace(/^./,x=>x.toUpperCase());

function Profile({row}:{row:Submission}){const d=row.form_data||{};const used=new Set(["student_name","grade","academic_year","birth_date","class_teacher","counselor","parent_name","contact",...groups.flatMap(g=>g.keys)]);const universities=[0,1,2].map(i=>({level:["DREAM","TARGET","SAFE"][i],university:d[`uni${i}`],program:d[`program${i}`],requirements:d[`requirements${i}`],funding:d[`funding${i}`]})).filter(x=>[x.university,x.program,x.requirements,x.funding].some(Boolean));const roadmap=Array.from({length:7},(_,i)=>({student:d[`road_student${i}`],school:d[`road_school${i}`],family:d[`road_family${i}`]})).filter(x=>x.student||x.school||x.family);const scores=Object.entries(d).filter(([k])=>/^s\d/.test(k));const other=Object.entries(d).filter(([k,v])=>!used.has(k)&&!/^s\d/.test(k)&&!/^uni\d|^program\d|^requirements\d|^funding\d|^road_/.test(k)&&v!==""&&v!=null);
return <article className="student-profile"><section className="profile-cover"><div className="avatar">{(row.student_name||"S").split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div><p className="eyebrow">REDBRIDGE STUDENT PROFILE</p><h1>{row.student_name||"Unnamed student"}</h1><p className="profile-headline">{pretty(d.major||d.school_direction||"University pathway in development")}</p><div className="profile-chips"><span>{row.application_number}</span><span>{row.status.toUpperCase()}</span><span>Grade {row.grade||"—"}</span><span>{row.academic_year||"—"}</span><span>{pretty(d.english_target||"English target pending")}</span></div></div></section><section className="profile-contact"><div><small>Date of birth</small><b>{pretty(d.birth_date)}</b></div><div><small>Homeroom teacher</small><b>{pretty(d.class_teacher)}</b></div><div><small>Counselor</small><b>{pretty(d.counselor)}</b></div><div><small>Next review</small><b>{pretty(d.next_review)}</b></div></section>
{groups.map(g=>{const items=g.keys.filter(k=>d[k]!==""&&d[k]!=null);return items.length?<section className="profile-section" key={g.title}><h2><i>{g.icon}</i>{g.title}</h2><div className="profile-fields">{items.map(k=><div className="profile-field" key={k}><small>{human(k)}</small><p>{pretty(d[k])}</p></div>)}</div></section>:null})}
{universities.length>0&&<section className="profile-section"><h2><i>3</i>Dream · Target · Safe universities</h2><div className="university-cards">{universities.map(x=><div key={x.level}><b>{x.level}</b><h3>{pretty(x.university)}</h3><p>{pretty(x.program)}</p><small>Requirements</small><p>{pretty(x.requirements)}</p><small>Budget / scholarship</small><p>{pretty(x.funding)}</p></div>)}</div></section>}
{roadmap.length>0&&<section className="profile-section"><h2><i>R</i>Admissions roadmap</h2><div className="timeline">{roadmap.map((x,i)=><div key={i}><b>{["Next 30 days","Next 3 months","Semester 1","Academic year","Summer","Next academic year","Before applications"][i]}</b><p><small>Student</small>{pretty(x.student)}</p><p><small>School</small>{pretty(x.school)}</p><p><small>Family</small>{pretty(x.family)}</p></div>)}</div></section>}
{scores.length>0&&<section className="profile-section"><h2><i>5</i>Academic ratings</h2><div className="score-pills">{scores.map(([k,v])=><span key={k}><small>{human(k)}</small><b>{pretty(v)}</b></span>)}</div></section>}
{other.length>0&&<section className="profile-section"><h2><i>+</i>Complete submitted details</h2><div className="profile-fields">{other.map(([k,v])=><div className="profile-field" key={k}><small>{human(k)}</small><p>{pretty(v)}</p></div>)}</div></section>}
<footer className="profile-footer"><span>Application {row.application_number} · Record {row.id}</span><span>Updated {new Date(row.updated_at||row.submitted_at).toLocaleString()}</span></footer></article>}

export default function AdminPage(){const[rows,setRows]=useState<Submission[]>([]),[selected,setSelected]=useState<string>(""),[query,setQuery]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[token,setToken]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);const base=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim().replace(/\/$/,"").replace(/\/rest\/v1.*$/,"");const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim();const filtered=useMemo(()=>rows.filter(r=>`${r.application_number} ${r.student_name} ${r.grade} ${r.status} ${r.form_data?.major||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);const current=rows.find(r=>r.id===selected)||filtered[0];
useEffect(()=>{const saved=sessionStorage.getItem("rb-admin-token");if(saved){setToken(saved);load(saved)}},[]);
async function load(accessToken=token){if(!base||!key||!accessToken)return;setLoading(true);setMessage("");try{const r=await fetch(`${base}/rest/v1/student_pathways?select=*&order=submitted_at.desc`,{headers:{apikey:key,Authorization:`Bearer ${accessToken}`}});if(!r.ok)throw new Error(r.status===401?"Session expired. Please sign in again.":`Unable to load submissions (HTTP ${r.status}).`);const result=await r.json();setRows(result);if(result[0])setSelected(s=>s||result[0].id)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load submissions.");if(String(e).includes("expired")){sessionStorage.removeItem("rb-admin-token");setToken("")}}finally{setLoading(false)}}
async function login(e:FormEvent){e.preventDefault();if(!base||!key){setMessage("Supabase configuration is missing.");return}setLoading(true);setMessage("");try{const r=await fetch(`${base}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const body=await r.json();if(!r.ok)throw new Error(body?.error_description||body?.msg||"Sign-in failed.");sessionStorage.setItem("rb-admin-token",body.access_token);setToken(body.access_token);setPassword("");await load(body.access_token)}catch(e){setMessage(e instanceof Error?e.message:"Sign-in failed.")}finally{setLoading(false)}}function logout(){sessionStorage.removeItem("rb-admin-token");setToken("");setRows([])}
if(!token)return <main className="admin-page"><div className="admin-login"><a className="admin-brand" href="/"><b>R</b><span>REDBRIDGE<small>PRIVATE ADMIN</small></span></a><p className="admin-kicker">AUTHORIZED ACCESS ONLY</p><h1>Student profiles</h1><p>Sign in to view private student submissions.</p><form onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={loading}>{loading?"Signing in…":"Sign in"}</button></form>{message&&<div className="admin-error">{message}</div>}</div></main>;
return <main className="profiles-admin"><aside className="profiles-sidebar"><div className="profiles-logo"><b>R</b><span>STUDENT PROFILES<small>PRIVATE ADMIN</small></span></div><div className="profiles-controls"><input aria-label="Search students" placeholder="Name or application no.…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>load()}>{loading?"…":"↻"}</button></div><p className="profiles-count">{filtered.length} PROFILE{filtered.length===1?"":"S"}</p><div className="profile-list">{filtered.map(r=><button className={current?.id===r.id?"active":""} onClick={()=>setSelected(r.id)} key={r.id}><span className="mini-avatar">{(r.student_name||"S")[0]}</span><span><b>{r.student_name||"Unnamed student"}</b><small>{r.application_number} · {r.status}</small><small>Grade {r.grade||"—"} · {pretty(r.form_data?.major||r.form_data?.school_direction)}</small></span></button>)}</div><button className="logout" onClick={logout}>Log out</button></aside><div className="profile-workspace">{message&&<div className="admin-error">{message}</div>}{!current&&!loading?<div className="empty-profile"><h2>No student profiles yet</h2><p>Saved drafts and submitted questionnaires will appear here.</p></div>:current&&<Profile row={current}/>}</div></main>}
