"use client";
import {FormEvent,useEffect,useState} from "react";

const steps=["Профиль ученика","Видение семьи","Голос ученика","Совместное решение","Roadmap до поступления"];
const subjects=["English","Mathematics","Physics","Chemistry","Biology","ICT / Computer Science","History / Social Sciences","Russian / Languages"];
const directions=["Medicine / Dentistry / Pharmacy","Engineering","Computer Science / AI / Data","Mathematics / Physics","Business / Economics / Finance","Law / Politics / International Relations","Psychology / Social Sciences","Architecture / Design / Creative Industries","Humanities / Languages","Sport / Sports Management","Пока не определено"];
type Data=Record<string,string|string[]>;

type Lang="ru"|"en"; let activeLang:Lang="ru";
const en:Record<string,string>={
"Профиль ученика":"Student profile","Видение семьи":"Family perspective","Голос ученика":"Student voice","Совместное решение":"Joint decision","Roadmap до поступления":"Admissions roadmap",
"Заполняет школа":"Completed by the school","Заполняет родитель":"Completed by the parent","Заполняет ученик":"Completed by the student","Школа · семья · ученик":"School · family · student","Итог встречи":"Meeting outcome","Совместное заполнение":"Completed together",
"Основная информация":"Basic information","Ученик (Ф.И.О.)":"Student’s full name","Класс":"Grade","Дата рождения":"Date of birth","Учебный год":"Academic year","Классный руководитель":"Homeroom teacher","Родитель / представитель":"Parent / guardian","Контакт":"Contact",
"Академический профиль":"Academic profile","Предмет":"Subject","Уровень":"Current level","Потенциал":"Potential","Мотивация":"Motivation","Динамика":"Progress","Растёт":"Improving","Стабильно":"Stable","Снижается":"Declining",
"Сильные стороны и развитие":"Strengths and development","Академические сильные стороны":"Academic strengths","Академические зоны развития / риски":"Academic development areas / risks","Личностные сильные стороны":"Personal strengths","Личностные зоны развития":"Personal development areas","Итоговый вывод школы":"School’s overall conclusion","Основное направление":"Primary pathway","Наблюдения, личностный профиль и факторы риска":"Observations, personal profile and risk factors",
"Ваше видение ребёнка":"Your view of the student","Какие 3 сильные стороны ребёнка вы считаете главными?":"What are the student’s three main strengths?","Какие качества или навыки необходимо улучшить?":"Which qualities or skills need improvement?","Любимые предметы и занятия вне школы":"Favourite subjects and activities outside school","Какие профессии ребёнок называл? Что семья не рассматривает?":"Which careers has the student mentioned? What will the family not consider?",
"Предпочитаемое направление":"Preferred study pathway","Выберите направления":"Select pathways","Приоритет 1":"Priority 1","Приоритет 2":"Priority 2","Приоритет 3":"Priority 3","География поступления":"Study destinations","Основные страны / регионы":"Primary countries / regions","Приемлемые варианты":"Acceptable options","Запасные варианты":"Backup options","Не рассматриваем":"Not considered","Важные условия":"Important conditions","Близость к Узбекистану":"Proximity to Uzbekistan","Безопасность":"Safety","Климат":"Climate","Визовые условия":"Visa conditions","Возможность работы":"Work opportunities","Родственники / контакты":"Relatives / contacts",
"Бюджет и ожидания":"Budget and expectations","Максимальный бюджет, USD / год":"Maximum budget, USD / year","Комфортный бюджет, USD / год":"Comfortable budget, USD / year","Готовность оплачивать без scholarship":"Ability to pay without a scholarship","Да":"Yes","Частично":"Partially","Нет":"No","Необходимый scholarship":"Required scholarship","Не требуется":"Not required","Ожидания от университета":"University priorities","Мировой рейтинг":"High global ranking","Сильная программа":"Strong degree programme","Scholarship / грант":"Scholarship / grant","Кампус и student life":"Campus and student life","Работа после выпуска":"Employment after graduation","Престиж бренда":"University reputation","Небольшие группы":"Small classes","Близость к семье":"Close to family","Research / магистратура":"Research / postgraduate study","Дополнительные финансовые ограничения":"Additional financial limitations",
"Твои интересы":"Your interests","Какие 3 предмета тебе действительно интересны?":"Which three subjects genuinely interest you?","Какие задачи ты любишь больше?":"Which tasks do you enjoy most?","Считать":"Calculating","Анализировать":"Analysing","Создавать":"Creating","Общаться":"Communicating","Помогать людям":"Helping people","Руководить":"Leading","Исследовать":"Researching","Какая профессия кажется интересной сейчас и почему?":"Which career interests you now, and why?","В какой стране или среде ты хотел(а) бы учиться?":"In which country or environment would you like to study?","Твоя готовность":"Your commitment","Заниматься дополнительно 5–10 часов в неделю?":"Study an additional 5–10 hours per week?","Скорее да":"Probably yes","Участвовать в олимпиадах, research, volunteering, internships?":"Participate in Olympiads, research, volunteering or internships?","Выборочно":"Selectively","Что ты готов(а) изменить уже в этом учебном году?":"What are you prepared to change this academic year?",
"Выбранный профиль":"Selected pathway","Основное направление / major":"Primary pathway / major","Альтернативное направление":"Alternative pathway","Приоритетные предметы":"Priority subjects","Целевой уровень English и дата":"Target English level and date","Внешние экзамены / certifications":"External exams / certifications","Другое":"Other","Ключевой профиль":"Key student profile","Университетская стратегия":"University strategy","DREAM — амбициозные":"DREAM — ambitious","TARGET — реалистичные":"TARGET — realistic","SAFE — высокая вероятность":"SAFE — high probability","Университет / страна":"University / country","Программа / major":"Programme / major","Требования":"Requirements","Бюджет / scholarship":"Budget / scholarship",
"План действий":"Action plan","Следующие 30 дней":"Next 30 days","Следующие 3 месяца":"Next 3 months","До конца 1-го семестра":"By the end of Semester 1","До конца учебного года":"By the end of the academic year","Лето":"Summer","Следующий учебный год":"Next academic year","До подачи applications":"Before applications","Что делает ученик":"Student actions","Что делает школа / Elsbeth":"School / Elsbeth actions","Что делает семья":"Family actions","KPI и риски":"KPIs and risks","Риски, которые могут помешать поступлению":"Risks that may affect admission","Итоговый комментарий School Counselor / Academic Director":"Final comment from the School Counselor / Academic Director","Следующая обязательная проверка roadmap":"Next mandatory roadmap review","Подтверждение совместного плана":"Joint plan confirmation","Согласен(на) с совместным планом":"I agree with the joint plan",
"Введите ответ":"Enter your answer","Введите ответ…":"Enter your answer…","Пока не определено":"Undecided"
};
const tr=(s:string)=>activeLang==="en"?(en[s]||s):s;

function Field({label,name,data,set,area=false}:{label:string,name:string,data:Data,set:(n:string,v:string|string[])=>void,area?:boolean}){return <label className="field"><span>{tr(label)}</span>{area?<textarea rows={4} value={(data[name] as string)||""} onChange={e=>set(name,e.target.value)} placeholder={tr("Введите ответ…")}/>:<input value={(data[name] as string)||""} onChange={e=>set(name,e.target.value)} placeholder={tr("Введите ответ")}/>}</label>}
function Choice({label,name,options,data,set,multi=false,max=99}:{label:string,name:string,options:string[],data:Data,set:(n:string,v:string|string[])=>void,multi?:boolean,max?:number}){const vals=(data[name] as string[])||[];return <fieldset><legend>{tr(label)}{multi&&max<99?activeLang==="en"?` — up to ${max}`:` — до ${max}`:""}</legend><div className="chips">{options.map(o=>{const yes=multi?vals.includes(o):data[name]===o;return <label className={yes?"on":""} key={o}><input type={multi?"checkbox":"radio"} name={name} checked={yes} onChange={()=>multi?set(name,yes?vals.filter(x=>x!==o):vals.length<max?[...vals,o]:vals):set(name,o)}/><span>{tr(o)}</span></label>})}</div></fieldset>}
function Section({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <section><h3><i>{n}</i>{tr(title)}</h3>{children}</section>}

export default function Home(){const[step,setStep]=useState(0),[lang,setLang]=useState<Lang>("ru"),[data,setData]=useState<Data>({academic_year:"2026–2027",counselor:"Elsbeth (Bess)"}),[status,setStatus]=useState("");activeLang=lang;const set=(n:string,v:string|string[])=>setData(d=>({...d,[n]:v}));useEffect(()=>{try{const x=localStorage.getItem("redbridge-pathway");if(x)setData(JSON.parse(x));const l=localStorage.getItem("redbridge-language") as Lang;if(l)setLang(l)}catch{}},[]);useEffect(()=>{localStorage.setItem("redbridge-pathway",JSON.stringify(data));localStorage.setItem("redbridge-language",lang);document.documentElement.lang=lang},[data,lang]);
async function submit(e:FormEvent){e.preventDefault();setStatus("Сохраняем…");const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key){setStatus("Демо-режим: черновик сохранён на этом устройстве. Подключите Supabase для отправки.");return}try{const r=await fetch(`${url}/rest/v1/student_pathways`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({student_name:data.student_name||null,grade:data.grade||null,academic_year:data.academic_year,form_data:data,status:"submitted"})});if(!r.ok)throw 0;localStorage.removeItem("redbridge-pathway");setStatus("Анкета успешно отправлена. Спасибо!")}catch{setStatus("Не удалось отправить. Черновик сохранён — попробуйте ещё раз.")}}
const go=(n:number)=>{setStep(n);scrollTo({top:0,behavior:"smooth"})};return <main><header><a href="#"> <b>R</b><span>REDBRIDGE<small>INTERNATIONAL SCHOOL</small></span></a><div className="header-tools"><p><i/>{lang==="en"?"Draft saves automatically":"Черновик сохраняется автоматически"}</p><div className="languages" role="group" aria-label="Language"><button className={lang==="ru"?"selected":""} onClick={()=>setLang("ru")}>Русский</button><button className={lang==="en"?"selected":""} onClick={()=>setLang("en")}>English</button></div></div></header><div className="shell"><aside><div className="year">2026 · 2027</div><h1>{lang==="en"?<>Individual<br/><em>pathway</em></>:<>Индивидуальная<br/><em>траектория</em></>}</h1><p>{lang==="en"?"Study profile, career and university strategy in one shared plan.":"Профиль обучения, карьера и университетская стратегия — в одном совместном плане."}</p><nav>{steps.map((s,i)=><button className={i===step?"active":i<step?"done":""} onClick={()=>go(i)} key={s}><b>{i<step?"✓":`0${i+1}`}</b><span>{tr(s)}<small>{tr(["Заполняет школа","Заполняет родитель","Заполняет ученик","Школа · семья · ученик","Итог встречи"][i])}</small></span></button>)}</nav><div className="bar"><span style={{width:`${(step+1)*20}%`}}/></div></aside><form onSubmit={submit}><div className="title"><span>{lang==="en"?`Part ${step+1} of 5`:`Часть ${step+1} из 5`}</span><p>{tr(["Заполняет школа","Заполняет родитель","Заполняет ученик","Совместное заполнение","Итог встречи"][step])}</p><h2>{tr(steps[step])}</h2></div>

{step===0&&<><Section n="A" title="Основная информация"><div className="grid"><Field label="Ученик (Ф.И.О.)" name="student_name" data={data} set={set}/><Field label="Класс" name="grade" data={data} set={set}/><Field label="Дата рождения" name="birth_date" data={data} set={set}/><Field label="Учебный год" name="academic_year" data={data} set={set}/><Field label="Классный руководитель" name="class_teacher" data={data} set={set}/><Field label="School Counselor" name="counselor" data={data} set={set}/><Field label="Родитель / представитель" name="parent_name" data={data} set={set}/><Field label="Контакт" name="contact" data={data} set={set}/></div></Section><Section n="1" title="Академический профиль"><p className="help">1 — требуется значительная поддержка · 3 — устойчивый средний · 5 — сильный уровень</p><div className="scores"><div className="score head"><b>Предмет</b><span>Уровень</span><span>Потенциал</span><span>Мотивация</span><span>Динамика</span></div>{subjects.map((s,i)=><div className="score" key={s}><b>{s}</b>{["level","potential","motivation"].map(k=><select key={k} value={(data[`s${i}${k}`] as string)||""} onChange={e=>set(`s${i}${k}`,e.target.value)}><option value="">—</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select>)}<select value={(data[`s${i}trend`] as string)||""} onChange={e=>set(`s${i}trend`,e.target.value)}><option value="">—</option><option>Растёт</option><option>Стабильно</option><option>Снижается</option></select></div>)}</div></Section><Section n="2" title="Сильные стороны и развитие"><div className="grid"><Field area label="Академические сильные стороны" name="academic_strengths" data={data} set={set}/><Field area label="Академические зоны развития / риски" name="academic_risks" data={data} set={set}/><Field area label="Личностные сильные стороны" name="personal_strengths" data={data} set={set}/><Field area label="Личностные зоны развития" name="personal_risks" data={data} set={set}/></div></Section><Section n="3" title="Итоговый вывод школы"><Choice label="Основное направление" name="school_direction" options={["STEM","Medicine / Life Sciences","Humanities / Social Sciences","Business / Economics","IT / CS","Creative / Arts","Undecided"]} data={data} set={set}/><Field area label="Наблюдения, личностный профиль и факторы риска" name="school_comment" data={data} set={set}/></Section></>}

{step===1&&<><div className="notice">Финансовый блок нужен не для оценки семьи, а для выбора реалистичных стран, scholarships и запасных вариантов.</div><Section n="1" title="Ваше видение ребёнка"><Field area label="Какие 3 сильные стороны ребёнка вы считаете главными?" name="parent_strengths" data={data} set={set}/><Field area label="Какие качества или навыки необходимо улучшить?" name="parent_improve" data={data} set={set}/><Field area label="Любимые предметы и занятия вне школы" name="parent_interests" data={data} set={set}/><Field area label="Какие профессии ребёнок называл? Что семья не рассматривает?" name="parent_career" data={data} set={set}/></Section><Section n="2" title="Предпочитаемое направление"><Choice multi max={3} label="Выберите направления" name="directions" options={directions} data={data} set={set}/><div className="grid"><Field label="Приоритет 1" name="priority1" data={data} set={set}/><Field label="Приоритет 2" name="priority2" data={data} set={set}/><Field label="Приоритет 3" name="priority3" data={data} set={set}/></div></Section><Section n="3" title="География поступления"><div className="grid"><Field label="Основные страны / регионы" name="countries_main" data={data} set={set}/><Field label="Приемлемые варианты" name="countries_ok" data={data} set={set}/><Field label="Запасные варианты" name="countries_safe" data={data} set={set}/><Field label="Не рассматриваем" name="countries_no" data={data} set={set}/></div><Choice multi label="Важные условия" name="country_conditions" options={["Близость к Узбекистану","Безопасность","Климат","Визовые условия","Возможность работы","Родственники / контакты"]} data={data} set={set}/></Section><Section n="4" title="Бюджет и ожидания"><div className="grid"><Field label="Максимальный бюджет, USD / год" name="budget_max" data={data} set={set}/><Field label="Комфортный бюджет, USD / год" name="budget_comfort" data={data} set={set}/></div><Choice label="Готовность оплачивать без scholarship" name="without_scholarship" options={["Да","Частично","Нет"]} data={data} set={set}/><Choice label="Необходимый scholarship" name="scholarship" options={["Не требуется","25%+","50%+","75%+","100% / full ride"]} data={data} set={set}/><Choice multi max={5} label="Ожидания от университета" name="uni_priorities" options={["Мировой рейтинг","Сильная программа","Scholarship / грант","Безопасность","Кампус и student life","Internships","Работа после выпуска","Престиж бренда","Небольшие группы","Близость к семье","Research / магистратура"]} data={data} set={set}/><Field area label="Дополнительные финансовые ограничения" name="financial_notes" data={data} set={set}/></Section></>}

{step===2&&<><div className="notice green">Решение не должно быть только решением взрослых. Здесь важны твои собственные интересы и готовность действовать.</div><Section n="1" title="Твои интересы"><Field area label="Какие 3 предмета тебе действительно интересны?" name="student_subjects" data={data} set={set}/><Choice multi label="Какие задачи ты любишь больше?" name="task_types" options={["Считать","Анализировать","Создавать","Общаться","Помогать людям","Руководить","Исследовать"]} data={data} set={set}/><Field area label="Какая профессия кажется интересной сейчас и почему?" name="student_career" data={data} set={set}/><Field area label="В какой стране или среде ты хотел(а) бы учиться?" name="student_country" data={data} set={set}/></Section><Section n="2" title="Твоя готовность"><Choice label="Заниматься дополнительно 5–10 часов в неделю?" name="extra_hours" options={["Да","Скорее да","Нет"]} data={data} set={set}/><Choice label="Участвовать в олимпиадах, research, volunteering, internships?" name="activities" options={["Да","Выборочно","Нет"]} data={data} set={set}/><Field area label="Что ты готов(а) изменить уже в этом учебном году?" name="student_change" data={data} set={set}/></Section></>}

{step===3&&<><Section n="1" title="Выбранный профиль"><div className="grid"><Field label="Основное направление / major" name="major" data={data} set={set}/><Field label="Альтернативное направление" name="major_alt" data={data} set={set}/><Field label="Приоритетные предметы" name="priority_subjects" data={data} set={set}/><Field label="Целевой уровень English и дата" name="english_target" data={data} set={set}/></div><Choice multi label="Внешние экзамены / certifications" name="exams" options={["IELTS / TOEFL","SAT / ACT","A-Level / IGCSE","AP","Другое"]} data={data} set={set}/><Choice label="Ключевой профиль" name="key_profile" options={["Academic excellence","Research","Olympiad","Leadership","Social impact","Sport","Arts","Entrepreneurship"]} data={data} set={set}/></Section><Section n="2" title="Университетская стратегия">{["DREAM — амбициозные","TARGET — реалистичные","SAFE — высокая вероятность"].map((x,i)=><div className="uni" key={x}><strong>{x}</strong><div className="grid"><Field label="Университет / страна" name={`uni${i}`} data={data} set={set}/><Field label="Программа / major" name={`program${i}`} data={data} set={set}/><Field label="Требования" name={`requirements${i}`} data={data} set={set}/><Field label="Бюджет / scholarship" name={`funding${i}`} data={data} set={set}/></div></div>)}</Section><Section n="3" title="Gap analysis"><Field area label="Academic results — статус, цель, действие" name="gap_academic" data={data} set={set}/><Field area label="English и entrance exams — статус, цель, действие" name="gap_exams" data={data} set={set}/><Field area label="Portfolio, research, leadership — статус, цель, действие" name="gap_portfolio" data={data} set={set}/></Section></>}

{step===4&&<><Section n="1" title="План действий">{["Следующие 30 дней","Следующие 3 месяца","До конца 1-го семестра","До конца учебного года","Лето","Следующий учебный год","До подачи applications"].map((x,i)=><div className="road" key={x}><strong>{x}</strong><div className="grid three"><Field label="Что делает ученик" name={`road_student${i}`} data={data} set={set}/><Field label="Что делает школа / Elsbeth" name={`road_school${i}`} data={data} set={set}/><Field label="Что делает семья" name={`road_family${i}`} data={data} set={set}/></div></div>)}</Section><Section n="2" title="KPI и риски"><div className="grid"><Field label="Academic average — цель" name="kpi_academic" data={data} set={set}/><Field label="English / IELTS — цель" name="kpi_english" data={data} set={set}/><Field label="Attendance / discipline" name="kpi_attendance" data={data} set={set}/><Field label="Portfolio activities" name="kpi_portfolio" data={data} set={set}/></div><Field area label="Риски, которые могут помешать поступлению" name="risks" data={data} set={set}/><Field area label="Итоговый комментарий School Counselor / Academic Director" name="final_comment" data={data} set={set}/><Field label="Следующая обязательная проверка roadmap" name="next_review" data={data} set={set}/></Section><section className="confirm"><h3>Подтверждение совместного плана</h3><p>Подтверждаю, что школа, семья и ученик ознакомились с текущей оценкой и согласовали направление работы. Roadmap может корректироваться.</p><label><input required type="checkbox"/> Согласен(на) с совместным планом</label></section></>}

<footer><button type="button" className="back" disabled={!step} onClick={()=>go(step-1)}>← {lang==="en"?"Back":"Назад"}</button>{step<4?<button type="button" className="next" onClick={()=>go(step+1)}>{lang==="en"?"Continue":"Продолжить"} →</button>:<button className="next" type="submit">{lang==="en"?"Submit questionnaire":"Отправить анкету"} →</button>}</footer>{status&&<div className="status">{status}</div>}</form></div></main>}
